#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/garbage.h"
#include "images/sonic.h"
#include "images/startscreen.h"
#include "images/greenhillzone.h"
#include "images/winscreen.h"
#include "images/bigring.h"
#include "images/badnik.h"
#include "images/gameover.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

char buffer[56];

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  struct sonic sonic1;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {

      case START:

        sonic1.row = 105;
        sonic1.col = 40;

        int badnikRow = 105;
        int badnikCol = 0;

        drawFullScreenImageDMA(startscreen);
        sprintf(buffer, "Press A (Z) to Start!");
        drawString(120, 50, buffer, RED);

        // state = ?

        if (KEY_DOWN(BUTTON_A, currentButtons) && !(KEY_DOWN(BUTTON_A, previousButtons))) {
          state = PLAY;
        }
        break;

      case PLAY:
        drawFullScreenImageDMA(greenhillzone);

        drawImageDMA(100, 200, 30, 30, bigring);
        drawImageDMA(sonic1.row, sonic1.col, 20, 20, sonic);
        drawImageDMA(badnikRow, badnikCol, 20, 20, badnik);

        badnikCol++;

        if (sonic1.col > 100) {
          sprintf(buffer, "You're halfway there!");
          drawString(150, 10, buffer, GREEN);
        }

        if (badnikCol == (sonic1.col - 20)) {
          state = LOSE;
        }

        if (KEY_DOWN(BUTTON_SELECT, currentButtons) && !(KEY_DOWN(BUTTON_START, previousButtons))) {
          state = START;
        }
        
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          sonic1.row -= 1;
        }

        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          sonic1.row += 1;
        }
        
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          sonic1.col -= 1;
        }

        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          sonic1.col += 1;
        }
        
        if (sonic1.row > 105) {
          sonic1.row = 105;
        }

        if (sonic1.col < 0) {
          sonic1.col = 0;
        }

        if (sonic1.col > 220) {
          sonic1.col = 220;
        }

        if ((sonic1.col > 180) && (sonic1.row > 80)) {
         state = WIN;
        }

        // state = ?
        break;
      case WIN:

        drawFullScreenImageDMA(winscreen);
        sprintf(buffer, "You got the S Rank!");
        drawString(100, 10, buffer, RED);
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
        }
        // state = ?
        break;

        case LOSE:
          drawFullScreenImageDMA(gameover);
          sprintf(buffer, "Game Over LOSER!");
          drawString(95, 70, buffer, GREEN);
          if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
          }
        break;

    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }


  return 0;
}